version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_api_db
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
